### ISSUE TITLE
Container fails to start [in CentOS]

### ISSUE THREAD

**Issue by acca301** [bitnami/bitnami-docker-mariadb#127]
To reproduce:

```sh
# docker run -ti --rm -e ALLOW_EMPTY_PASSWORD=yes --entrypoint=/bin/bash bitnami/mariadb
root@e4d901b163f2:/# ls -l /opt/bitnami/mariadb/data/test
total 4
-rw-r--r--. 1 root root 65 Jul  1 18:20 db.opt
root@e4d901b163f2:/# /app-entrypoint.sh /run.sh 

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
Error executing 'postInstallation': ENOENT: no such file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'
root@e4d901b163f2:/# ls -l /opt/bitnami/mariadb/data/test
ls: cannot access /opt/bitnami/mariadb/data/test/db.opt: No such file or directory
total 0
?????????? ? ? ? ?            ? db.opt
```

Note the screwed up directory entry for db.opt, while it was fine before /app_entrypoint.sh run.

Adding console.trace in /opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:
```javascript
[...]
  } catch (e) {
    if (options.abortOnError) {
// adding trace
console.trace(file);
      throw e;
    }
  }
[...]
```
yields

```sh
[...]
Trace: /opt/bitnami/mariadb/data/test/db.opt
    at _chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:31:9)
    at /opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:78:7
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at Object.chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:77:7)
    at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
    at _configurePermissions (/root/.nami/components/com.bitnami.mariadb/lib/component.js:137:13)
    at utilsFunctions.retry (/root/.nami/components/com.bitnami.mariadb/lib/component.js:173:13)
    at Object.retry (/root/.nami/components/com.bitnami.mariadb/lib/utils.js:28:14)
    at _.each (/root/.nami/components/com.bitnami.mariadb/lib/component.js:165:24)
Error executing 'postInstallation': ENOENT: no such file or directory, chown '/opt/bitnami/mariadb/data/test/db.opt'
```

```sh
$ docker info
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.40-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.65 GiB
Name: shift-node02
ID: FYYI:6RC3:DPO4:QG3O:SZCJ:VR3J:VREN:LR6U:EDH3:KYAR:4PON:MIQK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://1.16.0.1:3128
Https Proxy: http://1.16.0.1:3128
No Proxy: localhost,127.0.0.1
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 10.233.0.0/18
 127.0.0.0/8
Live Restore Enabled: false
```

It is a bit unclear what happened to directory entry, still digging. Any clue would be really appreciated.

**Comment by acca301** [comment]
The root of the problem is "Storage Driver: overlay2".

It seems to be broken in CentOS/RHEL kernels 4.4 and does not exist in 3.10. Switching to "Storage Driver: devicemapper" (LVM) brings the things back to sanity.

Note that OpenShift is using devicemapper/LVM.
