### ISSUE TITLE
Starting container fails with MariaDB postInstallation error

### ISSUE THREAD

**Issue by dArignac** [bitnami/bitnami-docker-mariadb#149]
**Description**

I start the `bitnami/mariadb:10.1` container, it immediately fails with this issue:

```
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb WARN  Allowing the "password" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | Error executing 'postInstallation': MySQL command failed to run. Error:
mariadb_1  |  ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")
mariadb_1  |
demo_mariadb_1 exited with code 1
```

**Steps to reproduce the issue:**

1. use this `docker-compose.yml` file:

```
version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bn_demo
      - MARIADB_DATABASE=bitnami_demo
      - ALLOW_EMPTY_PASSWORD=yes
```

2. ramp it up with `docker-compose up`
3. see the error 

**Version**

- Output of `docker version`: 

```
Docker version 17.05.0-ce, build 89658be
```

- Output of `docker info`:

```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 145
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702GiB
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I'm running this in a Vagrantbox with Centos 7.

**Comment by tompizmor** [comment]
hello @dArignac!

I have tried to reproduce the issue but I was unable. This is what I did:

1. Install [vagrant](https://www.vagrantup.com/downloads.html)
1. `vagrant init centos/7`
1. `vagrant up` 
1. `vagrant ssh`
1. Install [docker](https://docs.docker.com/install/linux/docker-ce/centos/) and [docker-compose](https://docs.docker.com/compose/install/#install-compose) 
1. Write your docker-compose.yml file
1. `docker-compose up`

```
[vagrant@ip-10-0-2-15 ~]$ docker-compose down -v
Removing vagrant_mariadb_1 ... done
Removing network vagrant_default
[vagrant@ip-10-0-2-15 ~]$ docker-compose up
Creating network "vagrant_default" with the default driver
Creating vagrant_mariadb_1 ... done
Attaching to vagrant_mariadb_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb WARN  Allowing the "password" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1  | mariadb INFO  ==> Creating database bitnami_demo...
mariadb_1  | mariadb INFO  ==> Creating user bn_demo...
mariadb_1  | mariadb INFO  ==> Granting access to bn_demo to the database bitnami_demo...
mariadb_1  | mariadb INFO
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Root User: root
mariadb_1  | mariadb INFO     Root Password: Not set during installation
mariadb_1  | mariadb INFO     Database: bitnami_demo
mariadb_1  | mariadb INFO     Username: bn_demo
mariadb_1  | mariadb INFO     Password: Not set during installation
mariadb_1  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 180628 10:06:06 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 180628 10:06:06 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
```

Do you think I am missing something?? Could you please try again setting the following env var in the docker-compose.yml? It will log more information.

`NAMI_LOG_LEVEL=trace8`

**Comment by dArignac** [comment]
Hi @tompizmor ,

thanks for your effort on trying to reproduce!
From what I see, you did what I did. What irritates me is that your output contains this `Installation parameters for mariadb:` part that mine does not have.

However, I updated my `docker-compose.yml` file with the log level environment variable you mentioned:

```
version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bn_demo
      - MARIADB_DATABASE=bitnami_demo
      - ALLOW_EMPTY_PASSWORD=yes
      - NAMI_LOG_LEVEL=trace8
``` 

The issue is still the same with it, but here is the output. As far as I can see there is nothing in it that would point me to the reason of the issue:

```
[vagrant@centos7_x86-64]$ docker-compose up
Creating demo_mariadb_1 ... done
Attaching to demo_mariadb_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: lib -> /opt/bitnami/mariadb/lib
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: lib -> /opt/bitnami/mariadb/lib
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: lib -> /opt/bitnami/mariadb/lib
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: lib -> /opt/bitnami/mariadb/lib
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: lib -> /opt/bitnami/mariadb/lib
mariadb_1  | mariadb TRACE [normalize] File normalization: bin -> /opt/bitnami/mariadb/bin
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [mkdir] File normalization: /opt/bitnami/mariadb/conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [mkdir] File normalization: /opt/bitnami/mariadb/data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [mkdir] File normalization: /opt/bitnami/mariadb/tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [mkdir] File normalization: /opt/bitnami/mariadb/logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/conf/my.cnf -> /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [exists] File normalization: /opt/bitnami/mariadb/conf/my.cnf -> /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/conf/my.cnf -> /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysql.sock -> /opt/bitnami/mariadb/tmp/mysql.sock
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/logs/mysqld.log -> /opt/bitnami/mariadb/logs/mysqld.log
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysql.sock -> /opt/bitnami/mariadb/tmp/mysql.sock
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysql.sock -> /opt/bitnami/mariadb/tmp/mysql.sock
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [exists] File normalization: /bitnami/mariadb/data/mysql -> /bitnami/mariadb/data/mysql
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb TRACE [normalize] File normalization: data -> /opt/bitnami/mariadb/data
mariadb_1  | mariadb TRACE [delete] File normalization: /opt/bitnami/mariadb/data/* -> /opt/bitnami/mariadb/data/*
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb WARN  Allowing the "password" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/conf/my.cnf -> /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [runProgram] Executing: /opt/bitnami/mariadb/bin/mysql_install_db --defaults-file=/opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [runProgram] Executing internal command: /opt/bitnami/mariadb/bin/mysql_install_db ["--defaults-file=/opt/bitnami/mariadb/conf/my.cnf"]
mariadb_1  | mariadb TRACE [runProgram] RESULT: {"code":0,"stderr":"2018-06-28 10:29:24 140123759949696 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.34-MariaDB) starting as process 47 ...\n2018-06-28 10:29:28 140058785134464 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.34-MariaDB) starting as process 76 ...\n2018-06-28 10:29:31 139722712819584 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.34-MariaDB) starting as process 105 ...\n","stdout":"Installing MariaDB/MySQL system tables in './data' ...\nOK\nFilling help tables...\nOK\nCreating OpenGIS required SP-s...\nOK\n\nTo start mysqld at boot time you have to copy\nsupport-files/mysql.server to the right place for your system\n\nPLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !\nTo do so, start the server, then issue the following commands:\n\n'/opt/bitnami/mariadb/bin/mysqladmin' -u root password 'new-password'\n'/opt/bitnami/mariadb/bin/mysqladmin' -u root -h 172.21.0.2 password 'new-password'\n\nAlternatively you can run:\n'/opt/bitnami/mariadb/bin/mysql_secure_installation'\n\nwhich will also give you the option of removing the test\ndatabases and anonymous user created by default.  This is\nstrongly recommended for production servers.\n\nSee the MariaDB Knowledgebase at http://mariadb.com/kb or the\nMySQL manual for more instructions.\n\nYou can start the MariaDB daemon with:\ncd '/opt/bitnami/mariadb' ; /opt/bitnami/mariadb/bin/mysqld_safe --datadir='./data'\n\nYou can test the MariaDB daemon with mysql-test-run.pl\ncd '/opt/bitnami/mariadb/mysql-test' ; perl mysql-test-run.pl\n\nPlease report any problems at http://mariadb.org/jira\n\nThe latest information about MariaDB is available at http://mariadb.org/.\nYou can find additional information about the MySQL part at:\nhttp://dev.mysql.com\nConsider joining MariaDB's strong and vibrant community:\nhttps://mariadb.org/get-involved/\n\n"}
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/logs/mysqld.log -> /opt/bitnami/mariadb/logs/mysqld.log
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/logs/mysqld.log -> /opt/bitnami/mariadb/logs/mysqld.log
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/logs/mysqld.log -> /opt/bitnami/mariadb/logs/mysqld.log
mariadb_1  | mariadb TRACE [normalize] File normalization: logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/logs/mysqld.log -> /opt/bitnami/mariadb/logs/mysqld.log
mariadb_1  | mariadb TRACE [exists] File normalization: /opt/bitnami/mariadb/logs -> /opt/bitnami/mariadb/logs
mariadb_1  | mariadb TRACE [exists] File normalization: /tmp -> /tmp
mariadb_1  | mariadb TRACE [exists] File normalization: /tmp -> /tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: conf -> /opt/bitnami/mariadb/conf
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/conf/my.cnf -> /opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [runProgram] Executing: null ./bin/mysqld_safe --defaults-file=/opt/bitnami/mariadb/conf/my.cnf
mariadb_1  | mariadb TRACE [runProgram] Executing internal command: '/bin/sh' ["-c","./bin/mysqld_safe --defaults-file=/opt/bitnami/mariadb/conf/my.cnf  &"]
mariadb_1  | mariadb TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":""}
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mariadb/tmp
mariadb_1  | mariadb TRACE [normalize] File normalization: /opt/bitnami/mariadb/tmp/mysqld.pid -> /opt/bitnami/mariadb/tmp/mysqld.pid
mariadb_1  | mariadb TRACE code: 0
mariadb_1  | mariadb TRACE stdout:
mariadb_1  |
mariadb_1  | mariadb TRACE stderr:
mariadb_1  |
mariadb_1  | Error executing 'postInstallation': MySQL command failed to run. Error:
mariadb_1  |  ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")
mariadb_1  |
mariadb_1  | nami    TRACE Error: Error executing 'postInstallation': MySQL command failed to run. Error:
mariadb_1  |  ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")
mariadb_1  |
mariadb_1  |     at execute (/.nami/components/com.bitnami.mariadb/lib/databases/mysql/index.js:77:13)
mariadb_1  |     at Object.dropDatabase (/.nami/components/com.bitnami.mariadb/lib/databases/mysql/index.js:314:5)
mariadb_1  |     at Service.$app.postInstallation (/.nami/components/com.bitnami.mariadb/main.js:77:22)
mariadb_1  |     at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
mariadb_1  |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
mariadb_1  |     at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
mariadb_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
mariadb_1  |     at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
mariadb_1  |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
mariadb_1  |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
demo_mariadb_1 exited with code 1
```

**Comment by tompizmor** [comment]
@dArignac I found the explanation of the issue in this [StackOverflow post](https://stackoverflow.com/questions/4584458/error-dropping-database-cant-rmdir-test-errno-17).

The question is why do you have files that are not from the test database inside the test database folder.

Are you persisting the data in some volume?
Have you tried to start from scratch in a different vagrant box?

**Comment by dArignac** [comment]
Hi @tompizmor,

afaik I don't have any file in the conainer as I am ramping it up on a clean system.

```
[vagrant@centos7_x86-64 bitnami]$ cat docker-compose.yml
version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bn_demo
      - MARIADB_DATABASE=bitnami_demo
      - ALLOW_EMPTY_PASSWORD=yes
[vagrant@centos7_x86-64 bitnami]$ docker images | grep bitnami
[vagrant@centos7_x86-64 bitnami]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[vagrant@centos7_x86-64 bitnami]$ docker-compose up
Pulling mariadb (bitnami/mariadb:10.1)...
10.1: Pulling from bitnami/mariadb
94921271ec3a: Pull complete
b8478a8bce2b: Pull complete
3ac236401bf6: Pull complete
ae56db4de94c: Pull complete
61cb3478fe41: Pull complete
da8911d81853: Pull complete
e5976781ce8c: Pull complete
d6ae838befae: Pull complete
871575d90832: Pull complete
ef6b7239cc46: Pull complete
Digest: sha256:c0e73fb2d9af51098e47516b862be2299a9fc4ff904547de9777ef47f7eaa128
Status: Downloaded newer image for bitnami/mariadb:10.1
Creating bitnami_mariadb_1 ... done
Attaching to bitnami_mariadb_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb WARN  Allowing the "password" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | Error executing 'postInstallation': MySQL command failed to run. Error:
mariadb_1  |  ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")
mariadb_1  |
bitnami_mariadb_1 exited with code 1
```

This is weird to me, but my other colleagues are having the same issue . We had it working last week with exactly this setup.
I'll try it in a other vagrantbox and get back to you.

**Comment by dArignac** [comment]
I tried it with a fresh vagrantbox, still the same issue.

**Comment by tompizmor** [comment]
Can you do the following so we can check the content of the `test` folder?

1. Run this docker-compose (`docker-compose up`)

```
version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    command: tail -f /dev/null
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bn_demo
      - MARIADB_DATABASE=bitnami_demo
      - ALLOW_EMPTY_PASSWORD=yes
```

2. Exec into the mariadb container (`docker exec -it CONTAINER_ID bash`) and run:

```
. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers
. /init.sh
nami_initialize mariadb
```

The nami_initialize command should fail with the same error but now you are inside the container and can debug some things. For example, run this commands and paste the output:

```
ls -alrth /opt/bitnami/mariadb/data/test/
```

**Comment by dArignac** [comment]
Hi @tompizmor ,

this is the output

```
I have no name!@f346050ace37:/$ . /opt/bitnami/base/functions
I have no name!@f346050ace37:/$ . /opt/bitnami/base/helpers
I have no name!@f346050ace37:/$ . /init.sh
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
I have no name!@f346050ace37:/$ nami_initialize mariadb
nami    INFO  Initializing mariadb
mariadb INFO  ==> Cleaning data dir...
mariadb INFO  ==> Configuring permissions...
mariadb INFO  ==> Validating inputs...
mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb WARN  Allowing the "password" input to be empty
mariadb INFO  ==> Initializing database...
Error executing 'postInstallation': MySQL command failed to run. Error:
 ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")

I have no name!@f346050ace37:/$ ls -alrth /opt/bitnami/mariadb/data/test/
ls: cannot access /opt/bitnami/mariadb/data/test/db.opt: No such file or directory
total 4.0K
??????????? ? ?    ?       ?            ? db.opt
drwxrwxr-x. 1 root root   19 Jul  5 17:55 .
drwxrwxr-x. 1 root root 4.0K Jul  5 17:55 ..
```

If I just start the container with the overridden `command`, then there is already this `db.opt` file in the test folder:

```
I have no name!@2131a21a1c94:/$ ls -lsa /opt/bitnami/mariadb/data/test/
total 4
0 drwxrwxr-x. 2 root root 19 Jun 29 10:48 .
0 drwxrwxr-x. 3 root root 17 Jun 29 10:48 ..
4 -rw-rw-r--. 2 root root 65 Jun 16 00:19 db.opt
```

**Comment by tompizmor** [comment]
Hi @dArignac,

It seems to be an issue with the docker storage driver as you can see at https://github.com/bitnami/bitnami-docker-mariadb/issues/92. The recommended solution in that case was switching to a different storage driver. Would be possible for you to try that?

**Comment by dArignac** [comment]
Hi @tompizmor ,

I'm sorry for the late reply.
Good to know where the issue comes from. And yes, I can switch to a different storage driver.

Thanks a lot for you help!
